# Generated by Django 4.1.1 on 2022-12-14 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_libreria_caratula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libreria',
            name='caratula',
        ),
    ]
