# Generated by Django 4.1.1 on 2022-10-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('titulo', models.CharField(max_length=30)),
                ('genero', models.CharField(max_length=30)),
                ('mes_venta', models.DateField()),
                ],
        ),
    ]